import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        
        <link
          rel="stylesheet"
          type="text/css"
          href="https://static.msscdn.net/static/common/1.2.0/pc.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://static.msscdn.net/ui/build/pc/css/common.css?202109290900"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://static.msscdn.net/skin/musinsa/css/magazine_common.css?202202150915"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://static.msscdn.net/skin/musinsa/css/store_common.css?202112011113"
        />
        <link
          rel="stylesheet"
          href="https://static.msscdn.net/platform/css/common.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://static.msscdn.net/skin/musinsa/css/layout.min.css?202201131000"
        />
        <link
          rel="stylesheet"
          href="https://image.msscdn.net/ui/musinsa/resources/common/css/icon.min.css?202101051200"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://static.msscdn.net/skin/musinsa/css/guide.min.css?202304261614"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://static.msscdn.net/skin/musinsa/css/style.min.css?202303211032"
        />{" "}
        <link
          rel="stylesheet"
          type="text/css"
          href="https://static.msscdn.net/skin/musinsa/css/sub.css?202305041110"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://static.msscdn.net/skin/musinsa/css/media_query.css?202010301640"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://static.msscdn.net/skin/musinsa/css/font.css?20170221"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://static.msscdn.net/skin/musinsa/css/new.css?202112010912"
        />
        <link
          href="https://static.msscdn.net/skin/musinsa/css/main.css?202204221324"
          rel="stylesheet"
          type="text/css"
        />        
        <link
          href="/style.css"
          rel="stylesheet"
          type="text/css"
        />

     
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
